import { Download, ImagePlus, LoaderCircle, Sparkles, X } from "lucide-react";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { generateImage, resolveImageEndpoint } from "../lib/image-generation";
import "./GenerationDialog.css";

/** Inputs for generating a personal image with the user's own image service. */
interface GenerationDialogProps {
  /** Whether the native modal should be visible. */
  open: boolean;
  /** Close the modal while retaining the in-memory connection settings. */
  onClose: () => void;
  /** Adopt the generated bytes as a session-local image owned by the parent. */
  onUse: (blob: Blob, name: string, model: string) => Promise<void>;
}

/** Optional output sizes accepted by the Images API form. */
type ImageSize = "" | "1024x1024" | "1536x1024" | "1024x1536";

/** Character description shared by the editable prompt and inspiration buttons. */
const CHARACTER_DESCRIPTION =
  "一张 DeepSeek 大肥鱼鲸鱼娘的 Q 版聊天表情包底图：蓝色渐变长发、蓝色眼睛、白色女仆头饰与蓝白女仆裙，搭配小鲸鱼装饰和鲸鱼尾巴，圆润可爱。";

/** Short, optional ideas that replace the prompt with a complete description. */
const PROMPT_IDEAS = [
  { label: "开心打招呼", action: "她开心地向前挥手。" },
  { label: "抱着奶茶", action: "她双手抱着一大杯奶茶，露出满足的表情。" },
  {
    label: "摸鱼充电",
    action: "她靠在蓝色鲸鱼抱枕上休息，表情放松，懒洋洋地伸展双手。",
  },
];

/** Builds a text-free sticker prompt that the user can freely edit. */
function makePrompt(action: string): string {
  return `${CHARACTER_DESCRIPTION}${action}主体完整居中，线条清晰，背景简洁，画面周围留出配字空间，不要文字、水印和边框。`;
}

/** Displays a resolved request address while tolerating incomplete form input. */
function endpointPreview(baseUrl: string): string {
  try {
    return resolveImageEndpoint(baseUrl);
  } catch {
    return "";
  }
}

/** Turns an operation error into a readable message without repeating the key. */
function readableError(cause: unknown, apiKey: string): string {
  const message =
    cause instanceof Error ? cause.message : "操作未完成，请重试。";
  const key = apiKey.trim();
  return key ? message.replaceAll(key, "[已隐藏]") : message;
}

/** Rejects truncated image bytes before enabling preview, download, or adoption. */
async function ensureDecodableImage(blob: Blob): Promise<void> {
  const url = URL.createObjectURL(blob);
  const image = new Image();
  try {
    image.src = url;
    await image.decode();
  } catch {
    throw new Error("返回的图片无法读取，请检查图像服务后再试。");
  } finally {
    URL.revokeObjectURL(url);
  }
}

/** Generate, preview, download, and adopt one image without persisting credentials. */
export default function GenerationDialog({
  open,
  onClose,
  onUse,
}: GenerationDialogProps) {
  const dialogRef = useRef<HTMLDialogElement>(null);
  const controllerRef = useRef<AbortController | null>(null);
  const openRef = useRef(open);
  const [baseUrl, setBaseUrl] = useState("https://api.openai.com/v1");
  const [model, setModel] = useState("");
  const [apiKey, setApiKey] = useState("");
  const [prompt, setPrompt] = useState(() =>
    makePrompt(PROMPT_IDEAS[0].action),
  );
  const [size, setSize] = useState<ImageSize>("");
  const [transparent, setTransparent] = useState(false);
  const [pending, setPending] = useState(false);
  const [applying, setApplying] = useState(false);
  const [result, setResult] = useState<Blob | null>(null);
  const [resultUrl, setResultUrl] = useState("");
  const [resultModel, setResultModel] = useState("");
  const [resultName, setResultName] = useState("我的大肥鱼");
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  openRef.current = open;

  useEffect(() => {
    const dialog = dialogRef.current;
    if (!dialog) return;
    if (open) {
      if (!dialog.open) dialog.showModal();
    } else {
      controllerRef.current?.abort();
      controllerRef.current = null;
      setPending(false);
      setApplying(false);
      setResult(null);
      setError("");
      setNotice("");
      if (dialog.open) dialog.close();
    }
  }, [open]);

  useEffect(() => {
    if (!result) {
      setResultUrl("");
      return;
    }
    // The modal owns only its preview URL; App creates its own when adopting the Blob.
    const url = URL.createObjectURL(result);
    setResultUrl(url);
    return () => URL.revokeObjectURL(url);
  }, [result]);

  useEffect(
    () => () => {
      controllerRef.current?.abort();
      controllerRef.current = null;
    },
    [],
  );

  /** Stops local waiting and invalidates callbacks from the previous operation. */
  function stopWaiting(): void {
    controllerRef.current?.abort();
    controllerRef.current = null;
    setPending(false);
    setApplying(false);
    setNotice("已停止等待，已提交的生成请求可能仍会计费。");
  }

  /** Dismisses the modal and discards its result while keeping form values in memory. */
  function dismiss(): void {
    controllerRef.current?.abort();
    controllerRef.current = null;
    setPending(false);
    setApplying(false);
    setResult(null);
    setError("");
    setNotice("");
    onClose();
  }

  /** Submit one user-requested generation; stale or aborted responses never update the UI. */
  async function submit(event: FormEvent<HTMLFormElement>): Promise<void> {
    event.preventDefault();
    if (controllerRef.current) return;
    const options = {
      baseUrl: baseUrl.trim(),
      model: model.trim(),
      apiKey: apiKey.trim(),
      prompt: prompt.trim(),
      size,
      transparent,
    };
    if (
      !options.baseUrl ||
      !options.model ||
      !options.apiKey ||
      !options.prompt
    ) {
      setError("请填写服务地址、模型、API Key 和画面描述。");
      return;
    }
    const controller = new AbortController();
    controllerRef.current = controller;
    setPending(true);
    setError("");
    setNotice("");
    setResult(null);

    try {
      const blob = await generateImage(options, controller.signal);
      if (
        controller.signal.aborted ||
        controllerRef.current !== controller ||
        !openRef.current
      )
        return;
      await ensureDecodableImage(blob);
      if (
        controller.signal.aborted ||
        controllerRef.current !== controller ||
        !openRef.current
      )
        return;
      setResult(blob);
      setResultModel(options.model);
      setNotice("底图已生成，可以下载或带进画布继续配字。");
    } catch (cause) {
      if (
        controller.signal.aborted ||
        controllerRef.current !== controller ||
        !openRef.current
      )
        return;
      setError(readableError(cause, options.apiKey));
    } finally {
      // A completed older request must not clear a newer request's loading state.
      if (controllerRef.current === controller && !controller.signal.aborted) {
        controllerRef.current = null;
        setPending(false);
      }
    }
  }

  /** Hands the Blob to the parent and closes only after successful adoption. */
  async function useResult(): Promise<void> {
    if (!result || controllerRef.current) return;
    const controller = new AbortController();
    controllerRef.current = controller;
    setApplying(true);
    setError("");
    setNotice("");
    try {
      await onUse(result, resultName.trim() || "我的大肥鱼", resultModel);
      if (
        controller.signal.aborted ||
        controllerRef.current !== controller ||
        !openRef.current
      )
        return;
      dismiss();
    } catch (cause) {
      if (
        controller.signal.aborted ||
        controllerRef.current !== controller ||
        !openRef.current
      )
        return;
      setError(readableError(cause, apiKey));
    } finally {
      if (controllerRef.current === controller && !controller.signal.aborted) {
        controllerRef.current = null;
        setApplying(false);
      }
    }
  }

  /** Downloads the original generated image, keeping the preview URL under modal ownership. */
  function downloadResult(): void {
    if (!result || !resultUrl) return;
    const extension =
      result.type === "image/jpeg"
        ? "jpg"
        : result.type === "image/webp"
          ? "webp"
          : "png";
    const link = document.createElement("a");
    link.href = resultUrl;
    link.download = `${resultName.trim() || "我的大肥鱼"}.${extension}`;
    link.click();
  }

  const endpoint = endpointPreview(baseUrl);
  const busy = pending || applying;

  return (
    <dialog
      ref={dialogRef}
      className="generation-dialog"
      aria-labelledby="generation-title"
      aria-describedby="generation-description"
      onCancel={(event) => {
        event.preventDefault();
        dismiss();
      }}
      onClose={() => {
        if (openRef.current) dismiss();
      }}
    >
      <header className="generation-heading">
        <span className="brand-mark">
          <Sparkles size={24} aria-hidden="true" />
        </span>
        <div>
          <h2 id="generation-title">把灵感画成底图</h2>
          <p id="generation-description">
            连接你的图像服务，为大肥鱼添一个新表情。
          </p>
        </div>
        <button
          type="button"
          className="icon-button"
          aria-label="关闭生成底图"
          onClick={dismiss}
        >
          <X size={21} />
        </button>
      </header>

      <div className="generation-body">
        <form
          className="generation-form"
          onSubmit={(event) => void submit(event)}
          aria-busy={pending}
        >
          <fieldset disabled={busy}>
            <legend className="generation-section-title">连接图像服务</legend>
            <label className="generation-field">
              <span>Base URL</span>
              <input
                type="url"
                value={baseUrl}
                autoComplete="off"
                spellCheck={false}
                required
                placeholder="https://api.openai.com/v1"
                onChange={(event) => setBaseUrl(event.target.value)}
              />
            </label>
            {endpoint && (
              <p className="generation-endpoint">
                请求地址 <code>{endpoint}</code>
              </p>
            )}
            <label className="generation-field">
              <span>模型</span>
              <input
                type="text"
                value={model}
                autoComplete="off"
                spellCheck={false}
                required
                placeholder="填写服务商的图像模型 ID"
                onChange={(event) => setModel(event.target.value)}
              />
            </label>
            <div className="generation-key-heading">
              <label htmlFor="generation-key">API Key</label>
              <button
                type="button"
                className="text-button"
                disabled={!apiKey}
                onClick={() => setApiKey("")}
              >
                清空
              </button>
            </div>
            <input
              id="generation-key"
              className="generation-key-input"
              type="password"
              value={apiKey}
              autoComplete="off"
              spellCheck={false}
              required
              placeholder="输入你的 API Key"
              onChange={(event) => setApiKey(event.target.value)}
            />
            <p className="generation-service-note">
              Prompt 与 API Key 直接发送到所填服务。Key
              仅保留在本次页面内存中，刷新即清除；服务需允许浏览器跨域请求（CORS）。
            </p>

            <label className="generation-field generation-prompt">
              <span>想画什么？</span>
              <textarea
                value={prompt}
                rows={6}
                required
                placeholder="描述大肥鱼的动作、表情和画面……"
                onChange={(event) => setPrompt(event.target.value)}
              />
            </label>
            <div
              className="generation-ideas"
              role="group"
              aria-label="底图灵感"
            >
              {PROMPT_IDEAS.map((idea) => (
                <button
                  type="button"
                  key={idea.label}
                  onClick={() => setPrompt(makePrompt(idea.action))}
                >
                  {idea.label}
                </button>
              ))}
            </div>

            <details className="generation-advanced">
              <summary>画面选项</summary>
              <div>
                <label className="generation-field">
                  <span>生成尺寸</span>
                  <select
                    aria-label="生成尺寸"
                    value={size}
                    onChange={(event) =>
                      setSize(event.target.value as ImageSize)
                    }
                  >
                    <option value="">使用服务默认值</option>
                    <option value="1024x1024">1024 × 1024 · 方形</option>
                    <option value="1536x1024">1536 × 1024 · 横向</option>
                    <option value="1024x1536">1024 × 1536 · 竖向</option>
                  </select>
                </label>
                <label className="generation-transparent">
                  <input
                    type="checkbox"
                    checked={transparent}
                    onChange={(event) => setTransparent(event.target.checked)}
                  />
                  <span>
                    请求透明背景<small>需模型支持透明 PNG 输出</small>
                  </span>
                </label>
              </div>
            </details>
          </fieldset>

          <div className="generation-submit-row">
            <button
              type="submit"
              className="button button-primary"
              disabled={
                busy ||
                !baseUrl.trim() ||
                !model.trim() ||
                !apiKey.trim() ||
                !prompt.trim()
              }
            >
              {pending ? (
                <LoaderCircle
                  className="generation-spinner"
                  size={18}
                  aria-hidden="true"
                />
              ) : (
                <Sparkles size={18} aria-hidden="true" />
              )}
              {pending ? "正在生成…" : result ? "再生成一张" : "生成底图"}
            </button>
            {pending && (
              <button
                type="button"
                className="button button-outlined"
                onClick={stopWaiting}
              >
                停止等待
              </button>
            )}
          </div>
          {error && (
            <p className="generation-message generation-error" role="alert">
              {error}
            </p>
          )}
          {notice && (
            <p className="generation-message" role="status">
              {notice}
            </p>
          )}
        </form>

        <section
          className="generation-result"
          aria-labelledby="generation-result-title"
          aria-busy={busy}
        >
          <div className="generation-result-heading">
            <h3 id="generation-result-title">你的新底图</h3>
            <span>本次会话</span>
          </div>
          <div className="generation-preview">
            {resultUrl ? (
              <img
                src={resultUrl}
                alt={`${resultName.trim() || "我的大肥鱼"}，生成底图预览`}
              />
            ) : (
              <div className="generation-placeholder" role="status">
                {pending ? (
                  <LoaderCircle
                    className="generation-spinner"
                    size={32}
                    aria-hidden="true"
                  />
                ) : (
                  <ImagePlus size={38} strokeWidth={1.4} aria-hidden="true" />
                )}
                <strong>
                  {pending ? "大肥鱼正在赶来…" : "给你的灵感留个位置"}
                </strong>
                <p>
                  {pending
                    ? "正在等待图像服务返回结果。"
                    : "写好描述，生成的底图会出现在这里。"}
                </p>
              </div>
            )}
          </div>
          {result && (
            <>
              <label className="generation-field">
                <span>给底图起个名字</span>
                <input
                  type="text"
                  value={resultName}
                  maxLength={60}
                  disabled={applying}
                  onChange={(event) => setResultName(event.target.value)}
                />
              </label>
              <p className="generation-result-model">模型：{resultModel}</p>
              <div className="generation-result-actions">
                <button
                  type="button"
                  className="button button-outlined"
                  disabled={busy || !resultUrl}
                  onClick={downloadResult}
                >
                  <Download size={17} aria-hidden="true" />
                  下载底图
                </button>
                <button
                  type="button"
                  className="button button-primary"
                  disabled={busy || !resultUrl}
                  onClick={() => void useResult()}
                >
                  <ImagePlus size={17} aria-hidden="true" />
                  {applying ? "正在载入…" : "使用这张底图"}
                </button>
              </div>
              <p className="generation-result-note">
                带进画布后，就可以加字、调色和导出表情包。
              </p>
            </>
          )}
        </section>
      </div>
    </dialog>
  );
}
